name: Build twtGUI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- install Qt ----------
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          arch: mingw-64
          version: 6.6.0
          modules: qtwidgets
          cache: true